logging:
  level: INFO
  appenders:
    - type: console
#      layout:
#        type: json

  loggers:
    nl.knaw.huygens.lobsang: DEBUG
    nl.knaw.huygens.lobsang.resources: TRACE

server:
  requestLog:
    appenders:
    - type: console
      layout:
        type: access-json

converterRegistry:
  default:
    "@class": nl.knaw.huygens.lobsang.core.converters.JulianConverter
  knownCalendars:
    gregorian:
      "@class": nl.knaw.huygens.lobsang.core.converters.GregorianConverter
    julian:
      "@class": nl.knaw.huygens.lobsang.core.converters.JulianConverter

placeRegistry:
  "@class": nl.knaw.huygens.lobsang.core.places.local.LocalPlaceRegistryFactory
  places:
    - name: 'Helsinki (populated place)'
      placeId: 'https://www.geonames.org/658225'
    - name: 'Opole (populated place)'
      placeId: 'https://www.geonames.org/3090048'
      parent: 'https://emdates.org/1'
    - name: 'Duchy of Opole'
      placeId: 'https://emdates.org/1'
      calendarPeriods:
        - calendar: 'Julian'
          endDate: '1584-01-29'
          provenance: 'EM Places'
        - calendar: 'Gregorian'
          startDate: '1582-02-08'
          provenance: 'EM Places'
      startOfYear:
        - when: --01-01
          since: 1584
    - name: 'Groningen (populated place)'
      placeId: 'https://www.geonames.org/2755251'
      calendarPeriods:
        - calendar: 'Julian'
          endDate: '1583-02-28'
          provenance: 'EM Places'
        - calendar: 'Gregorian'
          startDate: '1582-03-11'
          endDate: '1594-11-19'
          provenance: 'EM Places'
        - calendar: 'Julian'
          startDate: '1594-11-10'
          endDate: '1700-01-XX'
          provenance: 'EM Places'
        - calendar: 'Gregorian'
          startDate: '1700-01-XX'
          provenance: 'EM Places'
      startOfYear:
        - when: --01-01
          since: 1583




httpClient:
  timeout: 2000ms
  connectionTimeout: 2000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
