logging:
  level: INFO
  appenders:
    - type: console
#      layout:
#        type: json

  loggers:
    nl.knaw.huygens.lobsang: DEBUG
    nl.knaw.huygens.lobsang.resources: TRACE

server:
  requestLog:
    appenders:
    - type: console
      layout:
        type: access-json

knownCalendars:
- name: default
  class: nl.knaw.huygens.lobsang.core.converters.JulianConverter
- name: Gregorian
  class: nl.knaw.huygens.lobsang.core.converters.GregorianConverter
- name: Julian
  class: nl.knaw.huygens.lobsang.core.converters.JulianConverter
#- name: roman
#  class: nl.knaw.huygens.lobsang.core.converters.RomanConverter

places:
  - name: Austria, Bohemia
    calendarPeriods:
    - calendar: Julian
      end: 1584-01-06
    - calendar: Gregorian
      start: 1584-01-17
  - name: Austria, Brixen, Salzburg and Tyrol
    calendarPeriods:
    - calendar: Julian
      end: 1583-10-05
    - calendar: Gregorian
      start: 1583-10-16
  - name: Austria, Carinthia and Styria
    calendarPeriods:
    - calendar: Julian
      end: 1583-12-14
    - calendar: Gregorian
      start: 1583-12-25
  - name: Upper Austria, Alsace, Breisgau
    calendarPeriods:
    - calendar: Julian
      end: 1583-10-13
    - calendar: Gregorian
      start: 1583-10-24
  - name: Dutch Republic, Gelderland
    calendarPeriods:
    - calendar: Gregorian
      start: 1700-07-12
  - name: Dutch Republic, Friesland and Groningen
    calendarPeriods:
    - calendar: Julian
      end: 1700-12-31
    - calendar: Gregorian
      start: 1701-01-12
  - name: Groningen (City)
    calendarPeriods:
    - calendar: Julian
      end: 1583-02-28
    - calendar: Gregorian
      start: 1583-03-11
      end: 1594-11-19
    - calendar: Julian
      start: 1594-11-10
      end: 1699-12-31
    - calendar: Gregorian
      start: 1700-01-01
  - name: England and Wales
    calendarPeriods:
      - calendar: Julian
        end: 1752-09-02
      - calendar: Gregorian
        start: 1752-09-14
    startOfYear:
      - when: --03-25
        since: 1155
      - when: --01-01
        since: 1752
